# Sponge Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/Sponge

#====================#
#   General Config   #
#====================#
# None ;3

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 0.1